# Generated by Django 2.1.7 on 2019-03-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moviestable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('imdb_ID', models.CharField(max_length=20, null=True)),
                ('imdb_poster', models.URLField(null=True)),
                ('decription', models.TextField(max_length=200)),
                ('Movie_type', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resulttable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('rating_Movieid', models.CharField(max_length=20, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
    ]
