# Generated by Django 2.1.7 on 2019-03-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_moviestable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resulttable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('rating_Movieid', models.CharField(max_length=20, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='moviestable',
            old_name='imdb_url',
            new_name='imdb_poster',
        ),
        migrations.RemoveField(
            model_name='moviestable',
            name='rating',
        ),
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
