# Generated by Django 2.1.7 on 2019-03-25 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190325_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moviestable',
        ),
        migrations.DeleteModel(
            name='Resulttable',
        ),
    ]
